### ISSUE TITLE
Install fails on Python 3.7.0 under Windows 10

### ISSUE THREAD

**Issue by vuolter** [cmccandless/easy_getch#1]
```
C:\>pip install easy_getch
Collecting easy_getch
  Using cached https://files.pythonhosted.org/packages/aa/56/f5a994b5c0c326fef82101b39d5b4effe905b4200f6cf5b4edd329c7d82c/easy_getch-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-6ex5pgms\easy-getch\setup.py", line 17, in <module>
        long_description += changelog() + '\n'
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-6ex5pgms\easy-getch\setup.py", line 8, in changelog
        log =  subprocess.check_output('bin/changelog')
      File "c:\program files\python\3.7\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\program files\python\3.7\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files\python\3.7\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\program files\python\3.7\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by cmccandless** [comment]
@vuolter 
Should be fixed in v1.0.2. Please update and confirm.

**Comment by vuolter** [comment]
Sorry but still not installing.

PyPI release:
```
C:\>pip install easy_getch
Collecting easy_getch
  Downloading https://files.pythonhosted.org/packages/bb/96/c24a368ce5120893fe0731d016f236fc9e0fb92d9fbc60cc167b05c299c4/easy_getch-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-hcnk01i6\easy-getch\setup.py", line 4, in <module>
        from changelog import changelog
    ModuleNotFoundError: No module named 'changelog'
```

Master tarball:
```
C:\>pip install -e .
Obtaining file:///C:/Users/Walter/Desktop/easy-getch-master
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Walter\Desktop\easy-getch-master\setup.py", line 4, in <module>
        from changelog import changelog
      File "C:\Users\Walter\Desktop\easy-getch-master\changelog.py", line 24, in <module>
        TAG_PREV, TAG_CURRENT = command_output(['git', 'tag'])[-2:]
      File "C:\Users\Walter\Desktop\easy-getch-master\changelog.py", line 7, in command_output
        output = subprocess.check_output(args)
      File "c:\program files\python\3.7\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\program files\python\3.7\lib\subprocess.py", line 468, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'tag']' returned non-zero exit status 128.
```

I think you could remove all the changelog stuff and use just a setup.cfg file for settings (imo this seems the trend in python world).
About the second issue, it's due the missing git folder when you don't clone the repo but use pypi or whatever; further users may don't have git installed at all.

**Comment by cmccandless** [comment]
v1.0.5 now contains checks to skip building the changelog if there is no git installation.

> use just a setup.cfg file for settings (imo this seems the trend in python world).

The only reason I still haven't made the move to using setup.cfg in more of my projects is that it is still sometimes difficult to find solid documentation on the syntax needed for the cfg equivalents of some setup.py options.

**Comment by vuolter** [comment]
I sadly agree, documentation for setup.cfg is very poor (for pyproject.toml is literally non-existent).
The package still fails on installation (as expected due missing .git folder in a production-ready release 😢):
```
C:\>pip install easy-getch
Collecting easy-getch
  Downloading https://files.pythonhosted.org/packages/2d/7b/1624034a5979a57df5f951e93654af13385b94a9ef4cb77f7d036234e4da/easy_getch-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-8dedv28_\easy-getch\setup.py", line 4, in <module>
        from changelog import changelog
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-8dedv28_\easy-getch\changelog.py", line 24, in <module>
        TAG_PREV, TAG_CURRENT = command_output(['git', 'tag'])[-2:]
      File "C:\Users\Walter\AppData\Local\Temp\pip-install-8dedv28_\easy-getch\changelog.py", line 7, in command_output
        output = subprocess.check_output(args)
      File "c:\program files\python\3.7\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\program files\python\3.7\lib\subprocess.py", line 468, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'tag']' returned non-zero exit status 128.
```

**Comment by vuolter** [comment]
Now working fine. Thank you. 👍

**Comment by cmccandless** [comment]
No problem! Thanks for working through it!
